Path:
  # scene: "data/mp3d/"
  scene: "data/hm3d/"
  scene_dataset: "data/hm3d/hm3d_annotated_basis.scene_dataset_config.json"  
  # scene_dataset: "data/mp3d/mp3d.scene_dataset_config.json"  
  episode_data: "data/episode_task"
  # episode_data: null

  task_data: "data/task"
  step_task_data: "data/step_task"
  train_batch: ['/batch_1', '/batch_2', '/batch_3', '/batch_4', '/batch_5']
  val_batch: ['/batch_6']
  test_batch: ['/batch_7', '/batch_8']

  # train_batch: [ '/batch_1', '/batch_2']
  # val_batch: [ '/batch_6']
  # train_batch: [ ]
  # val_batch: [ ]


  # train_batch: [ '/batch_1', '/batch_2']
  # val_batch: [ '/batch_6']
  # test_batch: ['/batch_7', '/batch_8']

  # test_batch: [ '/rxr_test']
  # train_batch: [ '/rxr_test']
  # val_batch: [ '/rxr_test']

  split_by_scene: True

  save_checkpoints: "save_checkpoints"

  tensorboard_path: "run"
  output_dir: "output"
 

Train:
  mode: 'train'
  tensorboard: True
  # best_checkpoint: 'save_checkpoints/epoch_0step_264.pth' #ini kudu diisi kalo mode test
  best_checkpoint: null #ini kudu diisi kalo mode test
  resume_from_step: 0
  load_checkpoint: False
  save_ckpt_per_epochs: 10

  batch_size: 4
  num_epochs: 100
  ignoreid: -100
  max_step: 150
  gradient_accumulation_step: 2
  num_warmup_steps: 1000

  success_dis: 1
  dataset_type : 'not_rxr' #not rxr and rxr

Model:
  model_name: "LLM Model"
  pretrained_clip: "data/models/clip-vit-base-patch16"
  bert_model: "data/models/bert-large-uncased"
  pretrained_model_name_or_path: 'lmsys/vicuna-7b-v1.5'
  # pretrained_model_name_or_path: 'meta-llama/Llama-3.2-3B-Instruct'
  # pretrained_model_name_or_path: 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'
  resume_from_checkpoint: null # if you have a checkpoint and you want to load model from that state, here is the path you need to add
  from_scratch: False  # if your model is not vicuna 7b or llama 8b, set it to True
  feat_dropout: 0.4
  temperature: 1.0
  image_feat_size: 1024
  angle_feat_size: 4
  enc_full_graph: True
  num_pano_layers: 2
  max_memory: 20 # based on your vram
